name: take_stairs_when_visible
description: Move toward visible stairs to progress through dungeon
cooldown: 10.0
triggers:
  - type: vision_condition
    condition: stairs_visible
preconditions:
  - not_in_battle
actions:
  - type: move_to
    params:
      x: stairs_x
      y: stairs_y
fallback:
  - type: press
    params:
      keys: ["Up"]
priority: 15